-- Run this once in Supabase Dashboard > SQL Editor before using Advertising Income.

create table if not exists advertisement_incomes (
  id bigint generated by default as identity primary key,
  "receiptNo" text not null default '',
  date date not null,
  "eventId" bigint references events on delete set null,
  advertiser_en text not null default '',
  advertiser_gu text not null default '',
  description_en text not null default '',
  description_gu text not null default '',
  amount double precision not null check (amount > 0),
  "paymentMode" text not null default 'cash',
  "createdAt" text not null default '',
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

alter table advertisement_incomes
  add column if not exists "receiptNo" text not null default '';

alter table advertisement_incomes
  alter column "eventId" drop not null;

alter table advertisement_incomes enable row level security;

drop policy if exists "Users manage own advertisement incomes" on advertisement_incomes;

create policy "Users manage own advertisement incomes"
  on advertisement_incomes for all using (auth.uid() = user_id);

create or replace function reset_sequences() returns void language plpgsql security definer as $$
begin
  perform setval(pg_get_serial_sequence('settings',  'id'), coalesce((select max(id) from settings),  0) + 1, false);
  perform setval(pg_get_serial_sequence('purposes',  'id'), coalesce((select max(id) from purposes),  0) + 1, false);
  perform setval(pg_get_serial_sequence('donors',    'id'), coalesce((select max(id) from donors),    0) + 1, false);
  perform setval(pg_get_serial_sequence('events',    'id'), coalesce((select max(id) from events),    0) + 1, false);
  perform setval(pg_get_serial_sequence('donations', 'id'), coalesce((select max(id) from donations), 0) + 1, false);
  perform setval(pg_get_serial_sequence('expenses',  'id'), coalesce((select max(id) from expenses),  0) + 1, false);
  perform setval(pg_get_serial_sequence('advertisement_incomes', 'id'), coalesce((select max(id) from advertisement_incomes), 0) + 1, false);
end;
$$;
