-- Hanuman Dal — Supabase Schema
-- Run this in your Supabase Dashboard → SQL Editor → New Query
--
-- BEFORE running this, go to Authentication → Settings and:
--   1. Under "Email Auth" make sure "Enable Email Signup" is ON
--   2. Set "Confirm email" to OFF (for simple password-based auth)

-- ============================================================
-- TABLES
-- ============================================================

create table settings (
  id bigint generated by default as identity primary key,
  "orgName_en" text not null default 'Hanuman Dal',
  "orgName_gu" text not null default 'હનુમાન દળ',
  "address_en" text not null default '',
  "address_gu" text not null default '',
  phone text not null default '',
  "receiptPrefix" text not null default 'HD',
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  unique(user_id)
);

create table purposes (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_gu text not null,
  active smallint not null default 1,
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

create table donors (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_gu text not null,
  phone text not null default '',
  "address_en" text not null default '',
  "address_gu" text not null default '',
  "createdAt" text not null default '',
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

create table events (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_gu text not null,
  date date not null,
  description_en text not null default '',
  description_gu text not null default '',
  "createdAt" text not null default '',
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

create table donations (
  id bigint generated by default as identity primary key,
  "receiptNo" text not null,
  date date not null,
  "donorId" bigint references donors on delete set null,
  "donorName_en" text not null,
  "donorName_gu" text not null,
  phone text not null default '',
  amount double precision not null,
  "purposeId" bigint references purposes on delete set null,
  purpose_en text not null default '',
  purpose_gu text not null default '',
  "paymentMode" text not null default 'cash',
  "eventId" bigint references events on delete set null,
  note_en text not null default '',
  note_gu text not null default '',
  "createdAt" text not null default '',
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

create table expenses (
  id bigint generated by default as identity primary key,
  date date not null,
  "eventId" bigint references events on delete set null,
  category_en text not null default '',
  category_gu text not null default '',
  description_en text not null default '',
  description_gu text not null default '',
  "paidTo_en" text not null default '',
  "paidTo_gu" text not null default '',
  amount double precision not null,
  "paymentMode" text not null default 'cash',
  "createdAt" text not null default '',
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

create table advertisement_incomes (
  id bigint generated by default as identity primary key,
  "receiptNo" text not null default '',
  date date not null,
  "eventId" bigint references events on delete set null,
  advertiser_en text not null default '',
  advertiser_gu text not null default '',
  description_en text not null default '',
  description_gu text not null default '',
  amount double precision not null check (amount > 0),
  "paymentMode" text not null default 'cash',
  "createdAt" text not null default '',
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

create table in_kind_donations (
  id bigint generated by default as identity primary key,
  "receiptNo" text not null,
  date date not null,
  "donorId" bigint references donors on delete set null,
  "donorName_en" text not null,
  "donorName_gu" text not null,
  phone text not null default '',
  items jsonb not null default '[]',
  "eventId" bigint references events on delete set null,
  note_en text not null default '',
  note_gu text not null default '',
  status text not null default 'pending',
  "valuedAt" text,
  "donationId" bigint references donations on delete set null,
  "expenseId" bigint references expenses on delete set null,
  "createdAt" text not null default '',
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

create table opening_balances (
  id bigint generated by default as identity primary key,
  "purposeId" bigint references purposes on delete cascade,
  purpose_en text not null default '',
  purpose_gu text not null default '',
  "totalAmount" double precision not null default 0,
  "pendingAmount" double precision not null default 0,
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table settings  enable row level security;
alter table purposes  enable row level security;
alter table donors    enable row level security;
alter table events    enable row level security;
alter table donations enable row level security;
alter table expenses  enable row level security;
alter table advertisement_incomes enable row level security;
alter table in_kind_donations enable row level security;
alter table opening_balances enable row level security;

create policy "Users manage own settings"  on settings  for all using (auth.uid() = user_id);
create policy "Users manage own purposes"  on purposes  for all using (auth.uid() = user_id);
create policy "Users manage own donors"    on donors    for all using (auth.uid() = user_id);
create policy "Users manage own events"    on events    for all using (auth.uid() = user_id);
create policy "Users manage own donations" on donations for all using (auth.uid() = user_id);
create policy "Users manage own expenses"  on expenses  for all using (auth.uid() = user_id);
create policy "Users manage own advertisement incomes" on advertisement_incomes for all using (auth.uid() = user_id);
create policy "Users manage own in_kind_donations" on in_kind_donations for all using (auth.uid() = user_id);
create policy "Users manage own opening_balances" on opening_balances for all using (auth.uid() = user_id);

-- ============================================================
-- HELPER: reset identity sequences after backup import
-- ============================================================

create or replace function reset_sequences() returns void language plpgsql security definer as $$
begin
  perform setval(pg_get_serial_sequence('settings',  'id'), coalesce((select max(id) from settings),  0) + 1, false);
  perform setval(pg_get_serial_sequence('purposes',  'id'), coalesce((select max(id) from purposes),  0) + 1, false);
  perform setval(pg_get_serial_sequence('donors',    'id'), coalesce((select max(id) from donors),    0) + 1, false);
  perform setval(pg_get_serial_sequence('events',    'id'), coalesce((select max(id) from events),    0) + 1, false);
  perform setval(pg_get_serial_sequence('donations', 'id'), coalesce((select max(id) from donations), 0) + 1, false);
  perform setval(pg_get_serial_sequence('expenses',  'id'), coalesce((select max(id) from expenses),  0) + 1, false);
  perform setval(pg_get_serial_sequence('advertisement_incomes', 'id'), coalesce((select max(id) from advertisement_incomes), 0) + 1, false);
  perform setval(pg_get_serial_sequence('in_kind_donations', 'id'), coalesce((select max(id) from in_kind_donations), 0) + 1, false);
  perform setval(pg_get_serial_sequence('opening_balances', 'id'), coalesce((select max(id) from opening_balances), 0) + 1, false);
end;
$$;
