-- In-Kind Donations — Supabase Migration
-- Run this in your Supabase Dashboard → SQL Editor → New Query

create table in_kind_donations (
  id bigint generated by default as identity primary key,
  "receiptNo" text not null,
  date date not null,
  "donorId" bigint references donors on delete set null,
  "donorName_en" text not null,
  "donorName_gu" text not null,
  phone text not null default '',
  items jsonb not null default '[]',
  "eventId" bigint references events on delete set null,
  note_en text not null default '',
  note_gu text not null default '',
  status text not null default 'pending',
  "valuedAt" text,
  "donationId" bigint references donations on delete set null,
  "expenseId" bigint references expenses on delete set null,
  "createdAt" text not null default '',
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

alter table in_kind_donations enable row level security;
create policy "Users manage own in_kind_donations" on in_kind_donations for all using (auth.uid() = user_id);

-- Update the reset_sequences function to include the new table
create or replace function reset_sequences() returns void language plpgsql security definer as $$
begin
  perform setval(pg_get_serial_sequence('settings',  'id'), coalesce((select max(id) from settings),  0) + 1, false);
  perform setval(pg_get_serial_sequence('purposes',  'id'), coalesce((select max(id) from purposes),  0) + 1, false);
  perform setval(pg_get_serial_sequence('donors',    'id'), coalesce((select max(id) from donors),    0) + 1, false);
  perform setval(pg_get_serial_sequence('events',    'id'), coalesce((select max(id) from events),    0) + 1, false);
  perform setval(pg_get_serial_sequence('donations', 'id'), coalesce((select max(id) from donations), 0) + 1, false);
  perform setval(pg_get_serial_sequence('expenses',  'id'), coalesce((select max(id) from expenses),  0) + 1, false);
  perform setval(pg_get_serial_sequence('advertisement_incomes', 'id'), coalesce((select max(id) from advertisement_incomes), 0) + 1, false);
  perform setval(pg_get_serial_sequence('in_kind_donations', 'id'), coalesce((select max(id) from in_kind_donations), 0) + 1, false);
end;
$$;
