-- Run this in Supabase Dashboard → SQL Editor → New Query
-- Adds the opening_balances table for tracking past donation records

create table opening_balances (
  id bigint generated by default as identity primary key,
  "purposeId" bigint references purposes on delete cascade,
  purpose_en text not null default '',
  purpose_gu text not null default '',
  "totalAmount" double precision not null default 0,
  "pendingAmount" double precision not null default 0,
  user_id uuid not null default auth.uid() references auth.users on delete cascade
);

alter table opening_balances enable row level security;

create policy "Users manage own opening_balances"
  on opening_balances for all using (auth.uid() = user_id);

-- Update the reset_sequences function to include the new table
create or replace function reset_sequences() returns void language plpgsql security definer as $$
begin
  perform setval(pg_get_serial_sequence('settings',  'id'), coalesce((select max(id) from settings),  0) + 1, false);
  perform setval(pg_get_serial_sequence('purposes',  'id'), coalesce((select max(id) from purposes),  0) + 1, false);
  perform setval(pg_get_serial_sequence('donors',    'id'), coalesce((select max(id) from donors),    0) + 1, false);
  perform setval(pg_get_serial_sequence('events',    'id'), coalesce((select max(id) from events),    0) + 1, false);
  perform setval(pg_get_serial_sequence('donations', 'id'), coalesce((select max(id) from donations), 0) + 1, false);
  perform setval(pg_get_serial_sequence('expenses',  'id'), coalesce((select max(id) from expenses),  0) + 1, false);
  perform setval(pg_get_serial_sequence('advertisement_incomes', 'id'), coalesce((select max(id) from advertisement_incomes), 0) + 1, false);
  perform setval(pg_get_serial_sequence('in_kind_donations', 'id'), coalesce((select max(id) from in_kind_donations), 0) + 1, false);
  perform setval(pg_get_serial_sequence('opening_balances', 'id'), coalesce((select max(id) from opening_balances), 0) + 1, false);
end;
$$;
